steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mouth-metrics-docker-repo/auth-ui:latest'
  - '.'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mouth-metrics-docker-repo/auth-ui:latest'
