steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build \
    --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$$SECRETS_FIREBASE_API_KEY \
    --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$SECRETS_FIREBASE_AUTH_DOMAIN \
    --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$SECRETS_FIREBASE_PROJECT_ID \
    --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$SECRETS_FIREBASE_STORAGE_BUCKET \
    --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$SECRETS_FIREBASE_SENDER_ID \
    --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$$SECRETS_FIREBASE_APP_ID \
    --build-arg NEXT_PUBLIC_USERS_API_URL=$$SECRETS_USERS_API_URL \
    -t us-central1-docker.pkg.dev/$PROJECT_ID/mouth-metrics-docker-repo/auth-ui:latest \
    .
  secretEnv: ['SECRETS_FIREBASE_API_KEY', 'SECRETS_FIREBASE_AUTH_DOMAIN', 'SECRETS_FIREBASE_PROJECT_ID', 'SECRETS_FIREBASE_STORAGE_BUCKET', 'SECRETS_FIREBASE_SENDER_ID', 'SECRETS_FIREBASE_APP_ID', 'SECRETS_USERS_API_URL']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mouth-metrics-docker-repo/auth-ui:latest'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
    env: 'SECRETS_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'SECRETS_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
    env: 'SECRETS_FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
    env: 'SECRETS_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
    env: 'SECRETS_FIREBASE_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
    env: 'SECRETS_FIREBASE_APP_ID'
  - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_USERS_API_URL/versions/latest
    env: 'SECRETS_USERS_API_URL'
